---
# tasks file for ansible-role-hosts-inventory

- include_tasks: facts.yml
  when: hosts_ip_source == "facts"

- include_tasks: hostdata.yml
  when: hosts_ip_source == "hostdata"

- include_tasks: template.yml
  when: hosts_ip_source == "template"
