---
# tasks file for ansible-role-hosts-inventory

- include: facts.yml
  when: hosts_ip_source == "facts"

- include: hostdata.yml
  when: hosts_ip_source == "hostdata"

- include: template.yml
  when: hosts_ip_source == "template"
